name: Publicar paquete estadistico

on:
  push:
    branches:
      - main

jobs:
  publicar-paquete:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@laloohflorescruz'

      - name: Instalar dependencias y publicar
        run: npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
